# Site settings
title: Esporo
tagline: A comunidade brasileira de Spore
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"
lang: pt-BR
timezone: "America/Sao_Paulo"

email: contato@esporo.net
url: "https://esporo.net"
baseurl: ""

# Build settings
theme: steve-for-jekyll
markdown: kramdown
permalink: "/:year/:month/:title/"

steve:
  archives:
    date: "Posts de"
    tag: "Mais posts sobre…"
    category: "Posts arquivados em"
  date_formats:
    post: "%d/%m/%Y"
    archives:
      day: "%d/%m/%Y"
      month: "%m/%Y"
      year: "%Y"
  page_404: |+
    A página que você está procurando náo foi encontrada nessa URL. Por favor, tente buscar por ela ou [volte para a página inicial](https://esporo.net/).
  pagination:
    next_page: "&laquo; Posts mais recentes"
    prev_page: "Posts anteriores &raquo;"
    prev_post: "Anterior:"
    next_post: "Próximo:"
  post:
    tags: "Mais posts sobre…"
  search:
    label: "Pesquisar"
    placeholder: "O que você está procurando?"
    submit: "Pesquisar"

comments:
  title: Comentários
  form_title: Comentar
  date_format: "%d/%m/%Y às %k:%M"
  staticman_endpoint: "https://esporobot.herokuapp.com/v3/entry/github/esporo/esporo/main/comments"
  notice: |+ # Accepts Markdown
    Comentários são moderados, então o seu comentário pode demorar um pouco para aparecer no site.

    Lembre-se: os comentários seguem as mesmas [regras do Fórum](https://forum.esporo.net/d/50-regras-do-forum). Seja legal e respeite os outros.
  fields:
    name:
      label: Nome
      placeholder: "Seu nome"
    email:
      label: Endereço de email
      placeholder: "seu@email.net"
    website:
      label: Site ou blog
      placeholder: "https://seu-link.com/"
    message:
      label: Mensagem
      placeholder: Seu comentário
    submit: Enviar comentário

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

keep_files:
  - favicon.ico
  - uploads
  - assets/fonts
  - assets/icons
  - assets/images
  - assets/js

plugins:
  - jekyll-octicons

# Plugin: jekyll-paginate
paginate: 5
paginate_path: "/pagina/:num/"
seo_paginator_message: "Página %<current>s de %<total>s / "

# Plugin: jekyll-seo-tag
google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - https://twitter.com/esporo
    - https://www.youtube.com/user/esporotv
    - https://www.facebook.com/esporo

# Plugin: jekyll-compose
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      author: gaboo
      tags:
    posts:
      author: gaboo
      tags:
